spring:
  application:
    name: chatbot
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot
    username: postgres
    password: root
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
  redis:
    host: localhost
    port: 6379
